[package]
name = "spectacle"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]
edition = "2018"

[dependencies]
im = "14.3"
impl-tuples = { path = "impl-tuples" }

[features]
default = [ "collections" ]
collections = []

[workspace]
members = [
    ".",
    "impl-tuples",
]
