[package]
name = "impl-tuples"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]
edition = "2018"

[dependencies]
quote = "1.0.3"
syn = "1.0.17"


[lib]
proc-macro = true
